### ISSUE TITLE
Date picker overflowing container on mobile

### ISSUE THREAD

**Issue by misterjame** [merc1er/moonsama-gain-calculator#16]
![IMG_1172](https://user-images.githubusercontent.com/103995267/165123522-44a02af8-e506-4018-903b-2b481c741d89.PNG)

**Comment by merc1er** [comment]
Thanks.

Doing this:
<img width="509" alt="Screenshot 2022-04-25 at 22 42 58" src="https://user-images.githubusercontent.com/21960643/165124668-0c69fdbb-e359-4ddc-9109-90478b8b5147.png">
